//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBrokerCaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public int TipoMovId { get; set; }
        public int CajaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public Nullable<int> ReciboId { get; set; }
        public int MedioPagoId { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual MedioPago MedioPago { get; set; }
        public virtual TipoMovimientoCaja TipoMovimientoCaja { get; set; }
        public virtual Recibo Recibo { get; set; }
    }
}
