//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBrokerCaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int Id { get; set; }
        public int RamaId { get; set; }
        public string Poliza { get; set; }
        public string Endoso { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Cuota { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<System.DateTime> ProxVto { get; set; }
        public Nullable<System.DateTime> VtoConvenio { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> PlanillaId { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual PlanillaRendicionCobranza PlanillaRendicionCobranza { get; set; }
        public virtual Rama Rama { get; set; }
    }
}
